#source 'https://github.com/CocoaPods/Specs.git'
#platform :ios, '8.0'
#xcodeproj 'passwordmatrix.xcodeproj'

def shared_pods
platform :ios, '8.0'
	# Uncomment this line if you're using Swift or would like to use dynamic frameworks
	#use_frameworks!
	
	pod 'AFNetworking', '1.3.3'
	pod 'Reachability'
	pod 'OpenUDID'
	pod 'FXLabel'
	pod 'iRate'
	pod 'iNotify'
	pod 'MBProgressHUD'
	pod 'SVProgressHUD'
	#pod 'QR-Code-Encoder-for-Objective-C'
	pod 'NSDate-Extensions'
    pod 'GoogleAnalytics'
	#pod 'ChimpKit2'
	#pod 'Mixpanel'
	pod 'PDKeychainBindingsController'
	#pod 'Localytics-iOS-Client'
	#pod 'Facebook-iOS-SDK'
	#pod 'Parse', '1.5.0'
	pod 'Google-Mobile-Ads-SDK'
	pod 'ChartboostSDK'
	pod 'Flurry-iOS-SDK'
    
    #pod 'Firebase', '>= 2.5.0'
    #pod 'Firebase'
    #pod 'Firebase', '4.8.2'
    pod 'Firebase', '~> 4.8'
    #pod 'Firebase/AdMob'
    pod 'Firebase/Analytics'
    #pod 'Firebase/AppIndexing'
    #pod 'Firebase/Auth'
    #pod 'Firebase/Crash'
    pod 'Firebase/Database'
    #pod 'Firebase/DynamicLinks'
    #pod 'Firebase/Invites'
    #pod 'Firebase/Messaging'
    pod 'Firebase/RemoteConfig'
    #pod 'Firebase/Storage'

    pod 'HapticHelper'

end

target 'passwordmatrix' do
    shared_pods
end



